name: Release

on:
  push:
    branches:
      - master
    paths:
      - '.changeset/**'
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'registry.sh'

permissions:
  contents: write
  packages: read
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node (scoped registry)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://registry.npmjs.org/'
          scope: '@authzkit'
          always-auth: true
      - name: Prove npm auth
        run: |
          npm config get registry
          npm whoami
          npm ping
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm -r --sort --workspace-concurrency=1 --filter '{packages/*}' run build
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: pnpm -w changeset version
          publish: pnpm -w release
        env:
          # Prefer a PAT if provided to allow PR creation when org repos disallow GITHUB_TOKEN PRs
          # Set one of these secrets in repo/org settings: CHANGESETS_TOKEN or GH_PAT (scopes: repo)
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN || secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
